version: "{build}"

os:
- Windows Server 2012 R2
- Visual Studio 2015

build:
  verbosity: detailed

notifications:
- provider: Email
  to:
  - travis@simon.waldherr.eu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

clone_folder: c:\gopath\src\github.com\simonwaldherr\gwv

environment:
  GOPATH: c:\gopath

install:
- echo %PATH%
- echo %GOPATH%
- git submodule update --init --recursive
- go version
- go env
- go get -u -t simonwaldherr.de/go/gwv
- go get -v -t .

build_script:
- go test -v .
