os:
- osx
- linux
language: go
sudo: false
go:
- 1.6
- 1.7
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/onsi/gomega
- go get github.com/onsi/ginkgo
- pip install --user codecov
install:
- go get -t .
- go get -t simonwaldherr.de/go/gwv
- go get github.com/modocache/gover
script:
- go test -v -coverprofile=gover.coverprofile .
- $HOME/gopath/bin/gover
- $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
- go tool cover -html=gover.coverprofile -o coverage.html
- go tool cover -func=gover.coverprofile
- wget --post-file=coverage.html -q -O- "https://simonwaldherr.de/gocover/?repo=gwv&mode=save&key=$UPLOADSECRET&pull=$TRAVIS_PULL_REQUEST"
- go test -coverprofile=coverage.txt -covermode=atomic
after_success:
- cp coverprofile coverage.log
- codecov
notifications: 
  email: 
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
env:
  matrix:
    secure: bjYzYKskjYaWx4SXb/nxRnzVas0xGKxNzLZFGxcsmWSssvwzQFCg8TPaTgdDmfgaZvGw5rpyeAfOgf+3R1mjcPNM1Xv6KTeCLwNoh4Bdwc5HyN/Ppn7f/3zhKaGfFx2MXzwmo8fXrtZymXBfJsfk71v4qMuIpHeY/DCCRZD0vbA=
